### ISSUE TITLE
Formula for v2.4.0 not working

### ISSUE THREAD

**Issue by lucalianas** [TileDB-Inc/homebrew-stable#49]
Hi, I'm trying to install TileDB from homebrew and the Formula is not working.
It appears that the link to the package to be downloaded is broken, this is the output that I get when I try to install

```
❯ brew install tiledb-inc/stable/tiledb
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 7 casks.

Updating Homebrew...
==> Downloading https://github.com/TileDB-Inc/TileDB/releases/download/2.4.0/tiledb-macos-x86_64-release-2.4-baf64e1.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404
Error: tiledb: Failed to download resource "tiledb"
Download failed: https://github.com/TileDB-Inc/TileDB/releases/download/2.4.0/tiledb-macos-x86_64-release-2.4-baf64e1.tar.gz
```

I tried it both on Intel and Apple Silicon MacBook Pros, with the same identical result.

BTW, the formula should be updated also in order to download the proper arm64 package when running on Apple Silicon hardware.

**Comment by ihnorton** [comment]
I believe this has been addressed.
